export type TrickSubtest = 'figures' | 'equations' | 'latin' | 'gam' | 'pacing' | 'mindset';

/** core = must know, sharp = competitive edge, elite = the last few points. */
export type TrickLevel = 'core' | 'sharp' | 'elite';

export interface Trick {
  id: string;
  subtest: TrickSubtest;
  level: TrickLevel;
  title: string;
  body: string;
  /** engine rule tags (see ruleTagLabels) so weakness analytics can link a
   *  missed tag straight to the technique that fixes it */
  ruleTags?: string[];
  example?: string;
}

/**
 * Every trick here is derived from the actual generators in src/engine — the
 * movement/rotation/colour rules, the distractor builders, and the difficulty
 * bands. Figure coordinates are written 1-based: (row, column), (1,1) is the
 * top-left cell of the 4×4 grid. Matrices 1–4 are the given frames; Image 1 is
 * matrix 5 and Image 2 is matrix 6.
 */
export const TRICKS: Trick[] = [
  /* -------------------------------- figures ------------------------------- */
  {
    id: 'fig-shape-is-the-identity',
    subtest: 'figures',
    level: 'core',
    title: 'Track shapes, never colours',
    body: `Within one task every symbol has a different shape, and a shape never changes. Colour does change — it is one of the rules. The moment you think "the pink one", you have lost the thread; think "the triangle".`,
    ruleTags: ['fig.color.cycle2', 'fig.color.cycle3'],
  },
  {
    id: 'fig-one-symbol-at-a-time',
    subtest: 'figures',
    level: 'core',
    title: 'One symbol across four matrices, then the next',
    body: `Resolve a single symbol completely — position, then rotation, then colour — across all four given matrices before you even look at the second symbol. Scanning matrix by matrix instead of symbol by symbol is the single biggest time sink on hard tasks with four symbols.`,
    ruleTags: ['fig.multi.3symbols', 'fig.multi.4symbols'],
  },
  {
    id: 'fig-attribute-order',
    subtest: 'figures',
    level: 'core',
    title: 'Position, rotation, colour — in that order',
    body: `Position needs the most working memory, so do it while your head is clear. Rotation and colour are lookups once you know the cycle, and both survive being answered last.`,
  },
  {
    id: 'fig-read-coordinates-not-vibes',
    subtest: 'figures',
    level: 'core',
    title: 'Say the coordinates, do not eyeball the drift',
    body: `Read each position as (row, column) and name it silently: "(2,1), (2,2), (2,3)". "It drifted right" is how you end up choosing a decoy that is one cell short — which is exactly one of the decoys the generator builds.`,
  },
  {
    id: 'fig-diff-the-options-first',
    subtest: 'figures',
    level: 'core',
    title: 'The three options are one frame with one lie in it',
    body: `Both wrong options are the true frame with exactly ONE symbol altered — one attribute of it: position, rotation or colour. So cross-diff the three options before solving anything: whatever they agree on is true, and the disagreement names the only symbol you have to think about.`,
  },
  {
    id: 'fig-majority-vote',
    subtest: 'figures',
    level: 'elite',
    title: 'Per-attribute majority vote across the options',
    body: `Because each decoy corrupts one attribute of one symbol, the truth wins any 2-of-3 vote — unless both decoys attack the same attribute of the same symbol. Vote per (symbol, attribute); if every attribute has a clear majority, the option carrying all the majority values is the answer and you never derived a single rule.`,
    example: `Option A: triangle at (2,3), circle blue.
Option B: triangle at (2,3), circle green.
Option C: triangle at (3,3), circle blue.
Triangle majority = (2,3); circle majority = blue → Option A.`,
  },
  {
    id: 'fig-when-the-vote-ties',
    subtest: 'figures',
    level: 'elite',
    title: 'A tie tells you exactly what to solve',
    body: `When one symbol shows three different positions across the options, both decoys attacked it and the vote is dead — but you now know the only symbol worth simulating. Everything else on the board is already settled; solve that one symbol and ignore the rest of the grid.`,
  },
  {
    id: 'fig-image2-is-cheap',
    subtest: 'figures',
    level: 'core',
    title: 'Image 2 is not a bonus — the task only scores if both images are right',
    body: `Image 1 and Image 2 come from the same rule programs, one transition apart, so Image 2 costs seconds once the rules are yours. And it is not optional: a figure task is marked correct only when BOTH images are right, so solving Image 1 and abandoning the task scores exactly zero.`,
  },
  {
    id: 'fig-cross-check-two-images',
    subtest: 'figures',
    level: 'sharp',
    title: 'Your two picks must imply the same rules',
    body: `Image 1 and Image 2 are generated with fresh decoys, so a different symbol may be attacked in each. If the option you picked for Image 1 and the one for Image 2 cannot both come from one rule per symbol, one of them is wrong — and the inconsistency shows you which symbol to recheck.`,
  },
  {
    id: 'fig-bounce-corner-vs-edge',
    subtest: 'figures',
    level: 'core',
    title: 'A wall flips one component, a corner flips both',
    body: `A bouncing symbol reflects only the component that would leave the grid. A diagonal walker leaving the right edge keeps its vertical direction and only reverses the horizontal one; only in a corner do both flip. Confusing these produces precisely the decoy cell the generator offers you.`,
    ruleTags: ['fig.move.diagonal.bounce', 'fig.move.axis'],
    example: `Down-right walker at (3,4), moving (+1,+1):
next column would be 5 → out → horizontal flips to −1.
Vertical is untouched → it lands on (4,3), not (2,3).`,
  },
  {
    id: 'fig-bounce-never-parks',
    subtest: 'figures',
    level: 'sharp',
    title: 'A bounce costs no frame',
    body: `The symbol does not sit on the wall for a matrix and then turn. It occupies the wall cell in exactly one frame and is one cell back inside on the next. A right-mover starting at column 1 with step 1 runs columns 1, 2, 3, 4, 3, 2 — no repeat at the wall.`,
    ruleTags: ['fig.move.axis'],
  },
  {
    id: 'fig-shuttle-period-six',
    subtest: 'figures',
    level: 'elite',
    title: 'A straight-line shuttle has period 6',
    body: `A step-1 axis mover crossing the full width bounces back and forth with positional period 6: columns 1,2,3,4,3,2 then 1 again. If you know its column in matrix 1 you can generate every later column by walking that ladder — no direction bookkeeping needed.`,
    ruleTags: ['fig.move.axis'],
  },
  {
    id: 'fig-step2-midtransition-bounce',
    subtest: 'figures',
    level: 'elite',
    title: 'A 2-step mover can bounce inside one transition',
    body: `Step 2 means two single cells, each tested against the wall separately — so a symbol two cells from the wall goes to the wall and straight back, landing where it started. That apparent freeze is not a static symbol; it is a bounce you did not see.`,
    ruleTags: ['fig.move.axis'],
    example: `Right-mover, step 2, at column 3:
sub-step 1 → column 4 (the wall).
sub-step 2 → column 5 is off-grid → flip → column 3.
Net: it appears not to have moved at all.`,
  },
  {
    id: 'fig-slide-vs-bounce-first-contact',
    subtest: 'figures',
    level: 'sharp',
    title: 'The first wall contact settles slide vs bounce',
    body: `Only diagonal movers can slide. At the wall a slider cancels the blocked component and keeps the other — it keeps travelling ALONG the border row or column. A bouncer reverses the blocked component and leaves the wall diagonally. One frame pair after contact tells you which, and that answer holds for the rest of the task.`,
    ruleTags: ['fig.move.diagonal.slide', 'fig.move.diagonal.bounce'],
  },
  {
    id: 'fig-diagonal-parity',
    subtest: 'figures',
    level: 'elite',
    title: 'A bouncing diagonal never changes cell parity',
    body: `Every diagonal step changes row and column by one each, so (row + column) keeps its parity forever — bounces included, because a bounce is still a diagonal step. Cancelling one component at a wall (a slide) is the ONLY way to break that parity. Read it in the one direction that is valid: parity broken → the symbol slid. Parity intact does NOT prove it bounces — a diagonal that has not met a wall yet preserves parity whatever its wall rule is. What it does give you for free: once you know a symbol bounces, any option that puts it on the wrong parity is dead without simulation.`,
    ruleTags: ['fig.move.diagonal.bounce', 'fig.move.diagonal.slide'],
    example: `Start (4,1): 4+1 = 5, odd.
Every later cell of a bouncing diagonal is odd-sum: (3,2), (2,3), (1,4), (2,3)…
An option showing it on (2,4) (even) can only be a slide or a decoy nudge.`,
  },
  {
    id: 'fig-axis-parity',
    subtest: 'figures',
    level: 'elite',
    title: 'Axis movers flip parity, 2-step movers do not',
    body: `A step-1 axis mover changes (row + column) parity every single transition, so Image 1 (four transitions later) has the SAME parity as matrix 1. A step-2 mover never changes parity at all. A quick parity check kills the one-step-short and one-step-long decoys instantly.`,
    ruleTags: ['fig.move.axis'],
  },
  {
    id: 'fig-slider-dies-in-the-corner',
    subtest: 'figures',
    level: 'elite',
    title: 'A slider that reaches a corner stops forever',
    body: `In a corner both of a slider's components are cancelled, so it freezes on that cell for every remaining matrix — including both images. Do not expect the generator to rule this out: its "visibly changes in at least 4 of the 5 transitions" gate counts colour and rotation changes too, so a corner-parked slider that keeps turning and recolouring is perfectly legal and can stall early. If a diagonal reaches a corner and stops, it stays there.`,
    ruleTags: ['fig.move.diagonal.slide'],
  },
  {
    id: 'fig-mirror-decoy',
    subtest: 'figures',
    level: 'sharp',
    title: 'The mirrored diagonal is a manufactured trap',
    body: `For diagonal symbols the option builder replays the last transition with the COLUMN component of the direction negated — the true landing cell mirrored left–right about the previous cell. The row is right, the column is wrong by two. It looks exactly as plausible as the truth, so it cannot be spotted by feel: recompute the row and the column from the previous matrix and compare.`,
    ruleTags: ['fig.move.diagonal.bounce', 'fig.move.diagonal.slide'],
    example: `True: down-right walker at (2,2) → (3,3).
Mirror decoy: same row step, column step negated → (3,1).
Both are legal diagonal-looking cells; only arithmetic separates them.`,
  },
  {
    id: 'fig-perimeter-twelve-slots',
    subtest: 'figures',
    level: 'core',
    title: 'The border is a 12-cell ring',
    body: `A perimeter walker moves along the 12 border cells in order; corners are ordinary slots, not pauses. Counting the border as "4 + 4 + 4 + 4 = 16" is the classic miscount — there are twelve cells and the walk wraps around every twelve steps.`,
    ruleTags: ['fig.move.perimeter'],
  },
  {
    id: 'fig-perimeter-step-arithmetic',
    subtest: 'figures',
    level: 'sharp',
    title: 'Perimeter steps are ring arithmetic, not geometry',
    body: `Number the border 0–11 clockwise from the top-left and the whole rule becomes addition mod 12: clockwise step 2 means +2 per matrix, so from slot 10 you land on slot 0. Do not trace the path around the corner with your eyes; add.`,
    ruleTags: ['fig.move.perimeter'],
  },
  {
    id: 'fig-perimeter-x-plus-one',
    subtest: 'figures',
    level: 'elite',
    title: 'x+1 on the ring: Image 1 is 10 slots on, Image 2 is 3',
    body: `Total ring travel after f transitions is 1+2+…+f = f(f+1)/2. That gives 6 slots by matrix 4, 10 by Image 1, 15 = 3 (mod 12) by Image 2. So a clockwise accelerating walker sits 10 slots clockwise from its start (i.e. two slots counter-clockwise of it) in Image 1, and just 3 slots clockwise of the start in Image 2.`,
    ruleTags: ['fig.move.perimeter', 'fig.accel.x+1'],
    example: `Start slot 0 (top-left), clockwise, x+1:
matrix 2 = slot 1, matrix 3 = slot 3, matrix 4 = slot 6,
Image 1 = slot 10, Image 2 = slot 15 mod 12 = slot 3.`,
  },
  {
    id: 'fig-x-plus-one-is-four-then-five',
    subtest: 'figures',
    level: 'core',
    title: 'Under x+1 the hidden steps are 4 cells and 5 cells',
    body: `The three visible transitions moved 1, 2 and 3 cells. The transition into Image 1 moves 4, and the one into Image 2 moves 5 — not 5 and 6. Off-by-one here is the most expensive single mistake in the subtest, because it corrupts both images.`,
    ruleTags: ['fig.accel.x+1'],
  },
  {
    id: 'fig-x-plus-one-cumulative',
    subtest: 'figures',
    level: 'sharp',
    title: 'Accelerating totals: 6, 10, 15',
    body: `Measured from matrix 1, an x+1 symbol has travelled 6 cells by matrix 4, 10 by Image 1 and 15 by Image 2 (the triangular numbers). Computing from the start beats chaining four separate steps, because a single slip does not propagate.`,
    ruleTags: ['fig.accel.x+1'],
  },
  {
    id: 'fig-x-plus-one-detection',
    subtest: 'figures',
    level: 'sharp',
    title: 'Spot x+1 from the growing gap, not the first step',
    body: `Compare the 1→2 gap with the 3→4 gap. Constant step: both are the same. x+1: they are 1 and 3. A symbol whose gaps grow by exactly one each time is accelerating; a symbol with a big but constant gap is just a step-2 mover.`,
    ruleTags: ['fig.accel.x+1'],
  },
  {
    id: 'fig-hard-guarantees',
    subtest: 'figures',
    level: 'sharp',
    title: 'Hard tasks always contain an x+1 symbol and a loaded diagonal',
    body: `The hard generator guarantees one diagonal symbol that also rotates AND cycles colour (usually bouncing, sometimes sliding), plus one x+1 accelerating symbol — which may be an axis, diagonal or perimeter mover. Find those two first: they are where the marks are lost. Everything else in the task is medium-grade.`,
    ruleTags: [
      'fig.accel.x+1',
      'fig.move.diagonal.bounce',
      'fig.move.diagonal.slide',
      'fig.multi.4symbols',
    ],
  },
  {
    id: 'fig-rotation-period-four',
    subtest: 'figures',
    level: 'core',
    title: 'Rotation has period 4 — copy matrix 1',
    body: `A plain 90°-per-transition rotator returns to its original orientation after four transitions. Image 1 is four transitions after matrix 1, so its orientation is a copy of matrix 1's; Image 2 copies matrix 2's. You never have to decide clockwise vs counter-clockwise.`,
    ruleTags: ['fig.rotate.cw', 'fig.rotate.ccw'],
  },
  {
    id: 'fig-rotation-x-plus-one',
    subtest: 'figures',
    level: 'elite',
    title: 'Accelerating rotation turns 360° into Image 1',
    body: `With x+1 rotation, transition t turns 90t degrees. The step into Image 1 is transition 4 → 360° → the symbol looks EXACTLY as it did in matrix 4. The step into Image 2 is 450° → a single 90° turn on top. An option that shows a turn into Image 1 is the decoy.`,
    ruleTags: ['fig.rotate.cw', 'fig.rotate.ccw', 'fig.accel.x+1'],
    example: `Transitions: 90°, 180°, 270°, 360°, 450°.
Matrix 4 orientation = matrix 3 + 270°.
Image 1 = matrix 4 (+360° ≡ 0°). Image 2 = matrix 4 + 90°.`,
  },
  {
    id: 'fig-rotation-visible-shapes-only',
    subtest: 'figures',
    level: 'sharp',
    title: 'Only five shapes can carry a rotation rule',
    body: `Rotation is only ever applied to triangle, half-circle, half-square, T-shape and L-shape — the five shapes whose four quarter-turns look different. Circle, square, plus, star, X-cross, diamond and hourglass can NEVER carry a rotation rule (the hourglass is excluded too: it repeats every 180°, so a turn on it would be ambiguous). Do not waste a second hunting for a turn on a circle.`,
    ruleTags: ['fig.rotate.cw', 'fig.rotate.ccw'],
  },
  {
    id: 'fig-rotation-direction-decoy',
    subtest: 'figures',
    level: 'sharp',
    title: 'The reversed turn is always on the menu',
    body: `One standard decoy is the correct frame with the rotation applied the wrong way. Fix the direction once, from the matrix 1 → matrix 2 step, and then trust it: the rule never changes mid-task.`,
    ruleTags: ['fig.rotate.cw', 'fig.rotate.ccw'],
  },
  {
    id: 'fig-colour-two-cycle',
    subtest: 'figures',
    level: 'core',
    title: '2-colour alternation = frame parity',
    body: `An alternating symbol shows cycle position (frame index mod 2), so the colour depends only on whether the matrix number is odd or even. Image 1 (matrix 5, odd) repeats matrix 1's colour; Image 2 (matrix 6, even) repeats matrix 2's.`,
    ruleTags: ['fig.color.cycle2'],
  },
  {
    id: 'fig-colour-three-cycle',
    subtest: 'figures',
    level: 'core',
    title: '3-colour cycle = matrix number mod 3',
    body: `A three-colour cycle repeats every three matrices, so Image 1 shows matrix 2's colour and Image 2 shows matrix 3's. Both images are a straight lookup into the givens — you never need to remember the cycle order itself.`,
    ruleTags: ['fig.color.cycle3'],
  },
  {
    id: 'fig-colour-cycle-length-tell',
    subtest: 'figures',
    level: 'sharp',
    title: 'Tell a 2-cycle from a 3-cycle in one glance',
    body: `Look at matrix 3 and matrix 4 against matrix 1. Matrix 3 repeats matrix 1 → 2-cycle (A B A B). Matrix 4 repeats matrix 1 and matrix 3 was a third colour → 3-cycle (A B C A). That is the whole diagnosis.`,
    ruleTags: ['fig.color.cycle2', 'fig.color.cycle3'],
  },
  {
    id: 'fig-colour-phase-decoy',
    subtest: 'figures',
    level: 'sharp',
    title: 'Wrong colours are always neighbours in the cycle',
    body: `The colour decoy is the cycle stepped one too far or one too few — a stale or a skipped colour, never a random one. So a colour that is not in the symbol's observed cycle at all is not an option you will be offered; the discrimination is always between adjacent phases.`,
    ruleTags: ['fig.color.cycle2', 'fig.color.cycle3'],
  },
  {
    id: 'fig-direction-cycle-comes-home',
    subtest: 'figures',
    level: 'elite',
    title: 'A direction cycle returns the symbol to its start cell',
    body: `Every direction sequence in the rule set is a permutation of left, up, right and down — one of each. Four transitions therefore net out to zero displacement: in Image 1 the symbol is back on its matrix-1 cell, and in Image 2 on its matrix-2 cell. This is the fastest exact answer in the whole subtest.`,
    ruleTags: ['fig.move.cycle'],
    example: `Sequence right, down, left, up from (2,2):
matrix 2 = (2,3), matrix 3 = (3,3), matrix 4 = (3,2),
Image 1 = up → (2,2) = the matrix-1 cell. Image 2 = right → (2,3) = the matrix-2 cell.`,
  },
  {
    id: 'fig-direction-cycle-missing-direction',
    subtest: 'figures',
    level: 'elite',
    title: 'The unseen direction is the next one',
    body: `The four given matrices only show three of the cycle's four directions. Because the cycle uses each of left/up/right/down exactly once, the transition into Image 1 is the one direction you have NOT seen — and it must land the symbol back on its starting cell. Two independent derivations that have to agree: use them as a mutual check.`,
    ruleTags: ['fig.move.cycle'],
  },
  {
    id: 'fig-direction-cycle-one-cell',
    subtest: 'figures',
    level: 'core',
    title: 'Direction-cycle symbols always move exactly one cell',
    body: `A cycling symbol never accelerates and never takes two cells. If a candidate symbol jumps two cells in a transition, it is an axis or diagonal mover, not a cycler — that single observation eliminates a whole rule family.`,
    ruleTags: ['fig.move.cycle'],
  },
  {
    id: 'fig-perimeter-start-must-be-on-the-ring',
    subtest: 'figures',
    level: 'sharp',
    title: 'A centre-cell symbol is never a perimeter walker',
    body: `Perimeter movers must start on the border. A symbol sitting in one of the four central cells in matrix 1 cannot be one, so the moment you see it there, cross the ring rule off its candidate list.`,
    ruleTags: ['fig.move.perimeter'],
  },
  {
    id: 'fig-frozen-transition-means-bounce',
    subtest: 'figures',
    level: 'sharp',
    title: 'A symbol that seems not to move has bounced',
    body: `No symbol is ever given a "stay put" rule. So when a symbol holds its cell across a transition, its rule still fired and something cancelled it: a 2-step or accelerating mover that hit the wall and came straight back to where it started, or a diagonal slider stalled in a corner. Beware of reading it as "no rule": the generator's gate ("visibly changes in at least 4 of the 5 transitions") counts colour and rotation, not just position, so a frozen position is legal and is information, not noise.`,
  },
  {
    id: 'fig-no-legality-shortcuts',
    subtest: 'figures',
    level: 'core',
    title: 'You cannot eliminate an option by legality',
    body: `Symbols never overlap and never leave the grid — but every distractor frame is built to be legal too. There is no free elimination here, so do not spend time hunting for an impossible option; the decoys are all plausible.`,
  },
  {
    id: 'fig-off-trajectory-option',
    subtest: 'figures',
    level: 'sharp',
    title: 'A symbol off its own line is instantly dead',
    body: `Besides the near-misses, the option builder can simply nudge one symbol into a random neighbouring cell. That nudge is never checked against the symbol's own rule, so it often lands somewhere the rule cannot reach: an axis mover off its row or column, a bouncing diagonal on a cell of the wrong (row + column) parity. Such an option dies without any simulation at all.`,
    ruleTags: ['fig.move.axis', 'fig.move.diagonal.bounce'],
  },
  {
    id: 'fig-trust-the-simplest-fit',
    subtest: 'figures',
    level: 'sharp',
    title: 'The simplest rule that fits IS the rule',
    body: `Before a task is ever shown, the generator discards it if two rules consistent with the four given matrices would predict different images. So once you have a rule that fits all three visible transitions, stop hedging: whatever the "intended" rule was, yours predicts the same Image 1 and Image 2 — which is the only thing you are marked on.`,
  },
  {
    id: 'fig-easy-tasks-are-single-symbol',
    subtest: 'figures',
    level: 'core',
    title: 'Easy = one symbol, no rotation, no colour rule',
    body: `An easy figure task is a single symbol on an axis or the perimeter, moving 1 or 2 cells, with no rotation and no colour cycle. If you catch yourself tracking a colour change on an "easy" set, you have misread the difficulty — or the symbol.`,
  },
  {
    id: 'fig-count-symbols-first',
    subtest: 'figures',
    level: 'core',
    title: 'Count the symbols before you start',
    body: `Two or three symbols means medium; three or four means hard, with roughly two rules each. That count tells you your budget: a 4-symbol task will not be solved in 40 seconds, so decide up front whether to fight it or to bank the two easy symbols and vote on the rest.`,
    ruleTags: ['fig.multi.2symbols', 'fig.multi.3symbols', 'fig.multi.4symbols'],
  },
  {
    id: 'fig-anchor-on-the-loudest-symbol',
    subtest: 'figures',
    level: 'sharp',
    title: 'Start with the symbol the options disagree about',
    body: `Do not start with the easiest symbol — start with the one the three options actually dispute. Everything the options agree on is already free, so solving a quiet symbol earns you exactly nothing.`,
  },
  {
    id: 'fig-replay-in-the-review',
    subtest: 'figures',
    level: 'core',
    title: 'Use the frame player on every miss',
    body: `In review, step the six frames one at a time for the symbol you got wrong and watch the exact transition where your prediction diverged. Naming that transition ("I flipped the wrong component at the top wall") is what stops the mistake repeating; re-reading the rule text does not.`,
  },

  /* ------------------------------- equations ------------------------------ */
  {
    id: 'eq-count-the-letters',
    subtest: 'equations',
    level: 'core',
    title: 'Count letters per equation to sort the system',
    body: `One letter = an anchor, and it hands you a number outright. Two letters = a relation: either a plain definition, or (on three-letter systems) the combining equation that carries coefficients. Three or four letters = the hub, which only cracks once everything else is substituted. Solve in that order regardless of what is printed where.`,
    ruleTags: ['eq.hub'],
  },
  {
    id: 'eq-screen-order-is-shuffled',
    subtest: 'equations',
    level: 'core',
    title: 'The printed order is deliberately scrambled',
    body: `The equations are shuffled before they are displayed, so the first line on screen is very often the LAST one you should touch. Reading top to bottom and pushing forward is how a 40-second question turns into a 2-minute one.`,
  },
  {
    id: 'eq-anchor-first',
    subtest: 'equations',
    level: 'core',
    title: 'Find the anchor and cash it immediately',
    body: `The anchor is the only equation with a single letter in it, in a form like "7 + A = 14" or "A ÷ 3 = 4". It costs one subtraction or one multiplication and it unlocks the rest. Write its value into every other equation in your head before doing anything else.`,
  },
  {
    id: 'eq-no-anchor-means-hard',
    subtest: 'equations',
    level: 'elite',
    title: 'A four-letter system has NO anchor — that is the tell',
    body: `On four-variable tasks every equation contains at least two letters: three of them are pure relations and only the hub pins anything down. If you are hunting for a single-letter equation and cannot find one, stop hunting — switch to the root-expression method.`,
    ruleTags: ['eq.vars4', 'eq.hub', 'eq.subst.depth3'],
  },
  {
    id: 'eq-root-expression-method',
    subtest: 'equations',
    level: 'elite',
    title: 'Express everything in terms of one letter, then hit the hub',
    body: `Pick one letter as your parameter, walk the definitions to write each other letter as (multiple × parameter ± constant), and substitute all of them into the hub. The hub then collapses to a single linear equation in your parameter. This is literally how the generator built the task, run backwards.`,
    ruleTags: ['eq.vars4', 'eq.hub', 'eq.subst.depth3'],
    example: `2 × A = B      → B = 2A
B − 3 = C      → C = 2A − 3
3 × A − 1 = D  → D = 3A − 1
A + B − C + D = 26
→ A + 2A − (2A − 3) + (3A − 1) = 26
→ 4A + 2 = 26 → A = 6 (so B = 12, C = 9, D = 17).`,
  },
  {
    id: 'eq-hub-collapses-completely',
    subtest: 'equations',
    level: 'sharp',
    title: 'Every definition removes one letter from the hub',
    body: `The hub spans three or four of the letters (both sizes occur), and the three definitions express every letter in terms of one root — so once you substitute, the hub MUST reduce to a single unknown. If you still hold two, you skipped a definition or used one in the wrong direction. Go back rather than guessing.`,
    ruleTags: ['eq.hub', 'eq.subst.depth3'],
  },
  {
    id: 'eq-hub-signs',
    subtest: 'equations',
    level: 'elite',
    title: 'The hub is all ±1 coefficients — so it adds and subtracts cleanly',
    body: `Hub equations never multiply their letters; the first term is positive and the rest are plus or minus. That means you can add or subtract a definition straight into the hub to cancel a shared letter, without scaling anything first.`,
    ruleTags: ['eq.hub'],
  },
  {
    id: 'eq-sum-trick',
    subtest: 'equations',
    level: 'elite',
    title: 'Rearrange a definition into the hub and cancel a pair outright',
    body: `Every hub coefficient is ±1, so no scaling is ever needed. Rearrange a definition into the form "letter − letter = constant" and, when the hub carries those two letters with opposite signs, the pair cancels in one line. It beats formal substitution whenever the hub is long. (Definitions are always printed with the constant attached to one letter — "C − 1 = B" — so the rearranging is on you.)`,
    ruleTags: ['eq.hub'],
    example: `Hub:        A + B − C = 15
Definition: C − 1 = B        → B − C = −1
Substitute: A + (B − C) = 15 → A − 1 = 15 → A = 16, in one line.`,
  },
  {
    id: 'eq-division-reads-backwards',
    subtest: 'equations',
    level: 'core',
    title: '"B ÷ 2 = A" means B is the BIG one',
    body: `Read it as: B halved gives A, therefore B = 2A. Half the misses in this subtest are people halving when they should double. When the true value is even, the halved value is usually one of the options — that is the decoy for the direction you nearly went. When it is odd there is no halved value to offer, so do not go hunting for one: its absence tells you nothing about your answer.`,
    ruleTags: ['eq.op.div'],
  },
  {
    id: 'eq-divide-by-the-coefficient-last',
    subtest: 'equations',
    level: 'core',
    title: 'The last operation is the division you keep forgetting',
    body: `Combining equations look like "2 × C − 3 × A = 14". After substituting A you are holding 2 × C, not C — and the option builder always seeds DOUBLE the true answer whenever that fits 1–20, so stopping one step early lands you exactly on a decoy. You cannot spot it by looking, though: HALF the true answer is seeded too, so "the option that is double another option" is just as often the correct one. Do the division; do not shop the list for the trap.`,
    ruleTags: ['eq.combine', 'eq.op.mul'],
    example: `2 × C − 3 × A = 14, with A = 4
→ 2 × C = 14 + 12 = 26
→ C = 13. Here 26 is above the 1–20 bound, so it is not even on the list —
   the trap is absent, and you still had to do the division.`,
  },
  {
    id: 'eq-options-are-typed-errors',
    subtest: 'equations',
    level: 'core',
    title: 'The five options are a catalogue of your possible mistakes',
    body: `They are drawn from: the true value, the OTHER letters' values, the true value ±1 and ±2, its double, and its half when it is even (when it is odd the builder substitutes double-plus-one instead). Only if fewer than four of those survive the 1–20 bound does a random filler appear. So an option is not evidence — it is a diagnosis of the error that would produce it.`,
  },
  {
    id: 'eq-not-in-the-list-means-error',
    subtest: 'equations',
    level: 'core',
    title: 'If your answer is not an option, you are wrong — not the test',
    body: `The correct value is always among the five. When your number is missing, do not re-derive from scratch: first check you answered the letter that was actually asked, then check the last substitution. Those two account for nearly every miss.`,
  },
  {
    id: 'eq-wrong-letter-trap',
    subtest: 'equations',
    level: 'sharp',
    title: `Another letter's value is usually sitting in the option list`,
    body: `Every other letter's value goes into the decoy pool, and on most questions one of them makes the list — the punishment for solving the chain and answering the letter you finished with instead of the one asked. But the builder shuffles the pool and keeps only four decoys, so it is NOT on every question: its absence tells you nothing. Re-read the question line before you click.`,
  },
  {
    id: 'eq-two-var-target-is-derived',
    subtest: 'equations',
    level: 'elite',
    title: 'On two-letter systems the asked letter is never the anchored one',
    body: `A two-variable task is always an anchor plus a definition, and the target is the letter the definition produces — never the one the anchor pins. So if your first equation hands you the answer directly, you are looking at the wrong letter.`,
    ruleTags: ['eq.vars2', 'eq.subst.depth1'],
  },
  {
    id: 'eq-three-var-shape',
    subtest: 'equations',
    level: 'sharp',
    title: 'The three-letter system has a fixed shape',
    body: `It is always: one anchor, one definition that is specifically a multiplication or a division (never a plain ±), and one combining equation whose coefficients run 1–3 — and the target is the letter that appears ONLY in the combining equation. Recognising the shape tells you the solve order before you have read a single number.`,
    ruleTags: ['eq.vars3', 'eq.subst.depth2', 'eq.combine'],
  },
  {
    id: 'eq-divisibility-screen',
    subtest: 'equations',
    level: 'elite',
    title: 'Kill options with divisibility before you do any algebra',
    body: `"3 × A = B" says B is a multiple of 3; "B ÷ 4 = A" says B is a multiple of 4. Sweep the options against that and two or three of the five usually die in five seconds — sometimes leaving exactly one.`,
    ruleTags: ['eq.op.mul', 'eq.op.div'],
  },
  {
    id: 'eq-multiplier-bounds',
    subtest: 'equations',
    level: 'sharp',
    title: 'Multipliers bound the small letter hard',
    body: `Because every letter is at most 20, "10 × A = B" forces A into {1, 2} and B into {10, 20}. "5 × A = B" caps A at 4, and "4 × A = B" caps it at 5. On a choice question that bound alone can finish the job.`,
    ruleTags: ['eq.op.mul'],
  },
  {
    id: 'eq-parity-screen',
    subtest: 'equations',
    level: 'sharp',
    title: 'Parity is a free filter',
    body: `Any letter defined as 2 × something is even, full stop — every odd option for it is dead on sight. The same works in reverse: if the target must be odd, the doubled decoy is automatically eliminated.`,
    ruleTags: ['eq.op.mul'],
  },
  {
    id: 'eq-whole-number-invariant',
    subtest: 'equations',
    level: 'core',
    title: 'A fraction means you took a wrong turn',
    body: `Every letter is a whole number from 1 to 20 and the system has exactly one solution. So a fraction, a zero, a negative, or anything above 20 is not a hard question — it is a wrong step. Stop, re-read the equation you just used, and do not push on.`,
  },
  {
    id: 'eq-bounds-as-a-check',
    subtest: 'equations',
    level: 'core',
    title: 'Use 1–20 as a running sanity check, not just a rule',
    body: `Check each intermediate value against the bound the moment you produce it, not at the end. A letter that comes out as 26 tells you the error is in the step you just took — waiting until the end costs you the trail.`,
  },
  {
    id: 'eq-plug-the-options',
    subtest: 'equations',
    level: 'sharp',
    title: 'Sometimes the options are the fastest solver',
    body: `Five candidates, one bound of 1–20, and equations that are one line each: substituting an option into the shortest equation containing the target is often faster than solving forward, especially on four-letter hubs. Two options usually die on the first equation you try.`,
  },
  {
    id: 'eq-guess-and-check-from-the-target',
    subtest: 'equations',
    level: 'elite',
    title: 'Backwards guess-and-check on the hard system',
    body: `In choice mode on a four-letter task the asked letter IS the root of the definition chain — so take an option, run it forward through the three definitions, and see whether the hub balances. One pass per option, all integer arithmetic, no algebra.`,
    ruleTags: ['eq.vars4', 'eq.hub'],
  },
  {
    id: 'eq-substitute-numbers-immediately',
    subtest: 'equations',
    level: 'core',
    title: 'The instant a letter has a number, it stops being a letter',
    body: `Do not carry symbols any further than you must. As soon as A = 7, every A on the page is a 7 in your head. Symbolic manipulation under a 75-second clock is where sign errors breed.`,
  },
  {
    id: 'eq-sign-flip-discipline',
    subtest: 'equations',
    level: 'core',
    title: 'The ±1 and ±2 decoys are sign slips, wearing a disguise',
    body: `Moving a term across the equals sign flips it. The near-miss options exist precisely because that step is where people drop a sign under pressure. Say the move out loud in your head: "minus three moves over as plus three".`,
  },
  {
    id: 'eq-both-sides-are-fair-game',
    subtest: 'equations',
    level: 'core',
    title: 'The unknown is not always on the left',
    body: `Forms like "17 − A = B" and "B − 4 = A" are standard. Do not assume the letter you want is isolated on one side — read the whole equation before you decide what to do with it.`,
  },
  {
    id: 'eq-constants-run-to-99',
    subtest: 'equations',
    level: 'sharp',
    title: 'Printed numbers go up to 99, letters only to 20',
    body: `A constant of 87 in an equation is perfectly normal — it does not mean you misread anything. Keep the two ranges separate in your head: constants up to 99, solutions strictly 1–20.`,
  },
  {
    id: 'eq-back-substitute-the-last-step',
    subtest: 'equations',
    level: 'core',
    title: 'Verify against the equation you used LAST',
    body: `Checking your answer in the first equation proves almost nothing — that is the step you got right. Push the value back through the final substitution, the one with the coefficient or the sign change. Ten seconds, and it catches the errors that actually happen.`,
  },
  {
    id: 'eq-entry-mode-has-no-net',
    subtest: 'equations',
    level: 'sharp',
    title: 'Entry mode removes your safety net — budget for the check',
    body: `Entry mode asks for EVERY letter in the system and marks the task wrong unless all of them are right. With no options to compare against, the whole-number invariant and a back-substitution are the only things standing between you and a silent error. Practise in it precisely because it forces the verification habit; in choice mode the options do half of it for you.`,
  },
  {
    id: 'eq-mental-tables',
    subtest: 'equations',
    level: 'core',
    title: 'The only multipliers are 2, 3, 4, 5 and 10',
    body: `Definitions never multiply by 6, 7, 8 or 9, and hub/combining coefficients never exceed 3. Knowing those five times-tables cold up to 20 makes the arithmetic free and moves the whole task into pure structure.`,
    ruleTags: ['eq.op.mul'],
  },
  {
    id: 'eq-only-solve-what-is-asked',
    subtest: 'equations',
    level: 'sharp',
    title: 'Stop the moment the target is pinned',
    body: `In choice mode you get no marks for the other letters, so if the chain reaches the asked letter after two definitions, do not compute the fourth out of tidiness — that is 15 seconds you owe a harder task later. Entry mode is the exact opposite: it wants every letter and marks you wrong unless all of them are right, so there you finish the system.`,
  },
  {
    id: 'eq-depth-tells-effort',
    subtest: 'equations',
    level: 'sharp',
    title: 'The equation count predicts the work',
    body: `Two equations = one substitution. Three = two. Four = a chain of three plus a hub collapse. Read the count first and set your expectation, so a hard system does not feel like a mistake — it feels like the plan.`,
    ruleTags: ['eq.subst.depth1', 'eq.subst.depth2', 'eq.subst.depth3'],
  },
  {
    id: 'eq-definition-direction',
    subtest: 'equations',
    level: 'sharp',
    title: 'Definitions are symmetric — use whichever direction is cheaper',
    body: `"3 × C − 1 = B" lets you go C → B (multiply, subtract) or B → C (add, divide). Pick the direction that keeps you in whole numbers and away from fractions; the algebra is identical, the error rate is not.`,
    ruleTags: ['eq.op.mul'],
  },
  {
    id: 'eq-chain-source-hunt',
    subtest: 'equations',
    level: 'elite',
    title: 'On a four-letter task the asked letter IS the root',
    body: `The three definitions are built outward from one root letter — and that root is exactly the letter the question asks for. So you never have to hunt for the start of the chain: begin at the target and walk each definition outward, writing every other letter as (multiple × target ± constant). Note the definitions branch off the root rather than forming one straight line — two of them may both hang directly off the target.`,
    ruleTags: ['eq.vars4', 'eq.subst.depth3'],
  },
  {
    id: 'eq-hub-magnitude-check',
    subtest: 'equations',
    level: 'elite',
    title: 'Use the hub constant as a magnitude check',
    body: `If the hub adds four letters with plus signs and the constant is 12, the letters are small — an option of 18 for any of them is nonsense. Conversely a constant of 60-plus with mixed signs means at least one letter is near the top of the range. This filters options before any algebra.`,
    ruleTags: ['eq.hub'],
  },
  {
    id: 'eq-medium-anchor-is-small',
    subtest: 'equations',
    level: 'elite',
    title: 'On three-letter systems the anchored letter is 10 or less',
    body: `The generator keeps the anchor value at 10 or below so a multiplicative definition can still fit inside the 1–20 bound. So if your anchor comes out as 14, either you misread the equation or you are looking at a different task shape.`,
    ruleTags: ['eq.vars3'],
  },
  {
    id: 'eq-read-the-question-line',
    subtest: 'equations',
    level: 'core',
    title: 'Read which letter is asked BEFORE you start solving',
    body: `Knowing the target up front changes your route: you may not need the whole chain. Reading it afterwards is how you end up computing three letters and answering the wrong one — the decoy is right there waiting for you.`,
  },

  /* --------------------------------- latin -------------------------------- */
  {
    id: 'lat-count-the-givens',
    subtest: 'latin',
    level: 'core',
    title: 'Count the givens — it tells you the whole plan',
    body: `The clue count brackets the work. 15–17 givens: easy — the "?" falls to ONE elimination, so look only at its own row and column. 13: medium — two or three forced fills first. 9–11: hard — a chain of four or more, and the answer will not come from staring at the target. The bands overlap at exactly two counts: 14 is easy-or-medium and 12 is medium-or-hard, so on those, plan for the harder reading.`,
    ruleTags: ['lat.direct', 'lat.chain2', 'lat.chain4plus', 'lat.clues.sparse'],
  },
  {
    id: 'lat-the-cross-first',
    subtest: 'latin',
    level: 'core',
    title: 'Read the cross: the "?" row plus the "?" column',
    body: `Union the letters in the target's row and its column. Four distinct letters there means the fifth is the answer, immediately. On dense grids this is the entire task — 20 seconds, done.`,
    ruleTags: ['lat.direct'],
  },
  {
    id: 'lat-intersect-the-missing-lists',
    subtest: 'latin',
    level: 'core',
    title: 'Intersect what is missing from the row with what is missing from the column',
    body: `List the letters absent from the target's row, then the letters absent from its column. The answer must be in BOTH lists. Even on a sparse grid that intersection is usually down to two candidates before you have done any real deduction.`,
    ruleTags: ['lat.direct'],
  },
  {
    id: 'lat-hard-empties-the-cross-on-purpose',
    subtest: 'latin',
    level: 'elite',
    title: `On hard grids the target's own row and column are stripped first`,
    body: `The generator removes cells from the "?" row and column BEFORE it touches the rest of the grid on medium and hard. Those two lines are the sparsest in the puzzle by construction, so staring at the target is the one guaranteed way to waste a minute. The information is somewhere else — go and get it.`,
    ruleTags: ['lat.chain4plus', 'lat.clues.sparse'],
  },
  {
    id: 'lat-two-rules-only',
    subtest: 'latin',
    level: 'core',
    title: 'Two rules. There is no third.',
    body: `Elimination on a cell (its row and column already show four letters → the fifth goes there) and the hidden single (a letter that fits in only one cell of a row or column). Every task in this subtest is solvable with those two alone — no pairs, no boxes, no Sudoku folklore.`,
    ruleTags: ['lat.direct', 'lat.hiddenSingle.row', 'lat.hiddenSingle.col'],
  },
  {
    id: 'lat-hidden-single-mechanic',
    subtest: 'latin',
    level: 'core',
    title: 'How a hidden single actually works',
    body: `Take a letter missing from a row. Walk the empty cells of that row and cross off any whose COLUMN already contains that letter. One survivor means the letter is forced there — even if that cell has three candidates of its own.`,
    ruleTags: ['lat.hiddenSingle.row'],
    example: `Row 1 is completely empty; A sits in columns 2, 3, 4 and 5 elsewhere.
Then in row 1, A cannot go in columns 2–5 → it must be in column 1.
An empty row still yields a forced cell.`,
  },
  {
    id: 'lat-empty-row-still-talks',
    subtest: 'latin',
    level: 'core',
    title: 'An empty line is not a silent line',
    body: `Elimination tells you nothing about a cell in an empty row — but a hidden single can still pin a letter there through the columns. When the "?" sits in a bare row, stop eliminating and start asking which letter has nowhere else to go.`,
    ruleTags: ['lat.hiddenSingle.row', 'lat.hiddenSingle.col'],
  },
  {
    id: 'lat-four-of-a-letter',
    subtest: 'latin',
    level: 'sharp',
    title: 'A letter that appears four times is a free cell',
    body: `Four copies leave exactly one free row and one free column, so the fifth copy is pinned at their intersection — no candidate analysis at all. Scan for the most common letter first; on sparse grids that single fill often unlocks the chain.`,
    ruleTags: ['lat.hiddenSingle.row', 'lat.hiddenSingle.col'],
  },
  {
    id: 'lat-letter-census',
    subtest: 'latin',
    level: 'sharp',
    title: 'Run a letter census before you deduce anything',
    body: `Count A, B, C, D, E across the grid — five numbers, ten seconds. Attack the highest count: four is an instant fill, three is usually one hidden single away, and one or two are dead weight. That census IS your search order.`,
  },
  {
    id: 'lat-five-of-a-letter',
    subtest: 'latin',
    level: 'elite',
    title: 'A letter that already appears five times cannot be the answer',
    body: `Each letter appears exactly five times in a complete square. If the census shows five of a letter, cross it off the candidate list for the "?" without another thought — and if it shows five somewhere the row/column logic seems to want a sixth, you have misread a cell.`,
  },
  {
    id: 'lat-four-given-line',
    subtest: 'latin',
    level: 'core',
    title: 'A line with four letters gives its fifth for free',
    body: `Any row or column already holding four letters completes itself instantly. Do all of these before any real thinking: each one is free, and each one feeds a column you might need next.`,
    ruleTags: ['lat.direct'],
  },
  {
    id: 'lat-work-backwards-from-the-target',
    subtest: 'latin',
    level: 'elite',
    title: 'Ask what the "?" needs, then go and make it true',
    body: `The target resolves in exactly one of three ways: its cross shows four letters (elimination); or a letter missing from its ROW is blocked out of every other empty cell of that row; or a letter missing from its COLUMN is blocked out of every other empty cell of that column. Name the missing cell or the blocking letter that would make one of those true — that is your first deduction, and it aims the whole chain instead of wandering.`,
    ruleTags: ['lat.chain4plus', 'lat.hiddenSingle.row', 'lat.hiddenSingle.col'],
  },
  {
    id: 'lat-never-complete-the-square',
    subtest: 'latin',
    level: 'elite',
    title: 'Do not try to finish the grid',
    body: `Only the "?" is guaranteed to have a unique letter — the rest of the square may admit several valid completions. So a cell with two candidates is not a puzzle you failed to crack, it is a cell that is simply not determined. Leave it and look elsewhere.`,
  },
  {
    id: 'lat-never-branch',
    subtest: 'latin',
    level: 'core',
    title: 'Never guess a cell and follow it',
    body: `Trial-and-error is not one of the two rules, and because the grid can have several completions it may not even contradict itself — you can walk six cells down a wrong branch and never find out. Every fill you make must be forced.`,
  },
  {
    id: 'lat-chain-through-the-cross',
    subtest: 'latin',
    level: 'sharp',
    title: `Prefer deductions that land in the target's row or column`,
    body: `A forced fill somewhere far away is true but useless. A fill inside the "?" cross immediately shrinks the target's candidate set — and once you have used it, you can forget it. That is how you keep a 5-step chain inside working memory.`,
    ruleTags: ['lat.chain4plus'],
  },
  {
    id: 'lat-three-facts-max',
    subtest: 'latin',
    level: 'elite',
    title: 'Hold three derived cells, no more',
    body: `Note-taking is not allowed, so memory is your scratchpad and it holds about three items. Encode each as a sentence — "row 4 takes a C in column 2" — not as a picture. If you need a fourth fact, you are on the wrong chain: the grid is still on screen, so drop everything and restart from a better cell.`,
    ruleTags: ['lat.chain4plus'],
  },
  {
    id: 'lat-re-derive-dont-recall',
    subtest: 'latin',
    level: 'sharp',
    title: 'Re-deriving beats remembering',
    body: `Reconstructing a forced cell from the grid costs three seconds. Misremembering one costs the question, and you will never notice you did it. When in doubt, look again — the grid never lies to you and your memory sometimes does.`,
  },
  {
    id: 'lat-say-the-missing-letters-in-order',
    subtest: 'latin',
    level: 'sharp',
    title: 'Recite missing letters in A-to-E order',
    body: `Scanning a line for what is absent is exactly the moment you drop a letter. Always run A, B, C, D, E in that fixed order and say the gaps: "B... and E". The ordering is what makes the scan reliable without notes.`,
  },
  {
    id: 'lat-transpose-when-stuck',
    subtest: 'latin',
    level: 'core',
    title: 'If rows are dry, switch to columns',
    body: `Both inference rules work identically along rows and along columns, and the grids are built with no bias between the two — a hidden single is as likely to live in a column as in a row. A dry row scan is not a dead end; it is the signal to turn the grid ninety degrees in your head.`,
    ruleTags: ['lat.hiddenSingle.row', 'lat.hiddenSingle.col'],
  },
  {
    id: 'lat-densest-cell-first',
    subtest: 'latin',
    level: 'sharp',
    title: 'Fill the cell where a dense row meets a dense column',
    body: `The cheapest cell in the grid is the empty one whose row AND column are both nearly full — it usually falls to plain elimination, and it feeds two lines at once. Find that intersection before you look anywhere else.`,
    ruleTags: ['lat.direct'],
  },
  {
    id: 'lat-rescan-the-two-lines',
    subtest: 'latin',
    level: 'sharp',
    title: 'After every fill, rescan just the two lines it touched',
    body: `A new letter can only change the row and the column it landed in. Rescanning the whole grid after each fill is what makes a 4-step chain feel like twenty steps; rescanning two lines keeps it at four.`,
  },
  {
    id: 'lat-target-candidate-test',
    subtest: 'latin',
    level: 'sharp',
    title: 'Test the five candidates against the target directly',
    body: `The "?" has at most five candidates, and each can be tested in one pass: is that letter already in the row? In the column? Could it be a hidden single here? On easy tasks the first two questions finish it before you have formed any plan at all.`,
    ruleTags: ['lat.direct'],
  },
  {
    id: 'lat-two-candidates-then-hidden-single',
    subtest: 'latin',
    level: 'sharp',
    title: 'Two candidates left? A hidden-single check decides it.',
    body: `When the cross narrows the "?" to exactly two letters, do not go back to elimination. Take one and ask whether it fits anywhere ELSE in the target's row — then in the target's column. Whichever of the two is blocked out of every other cell of a line is forced here. If NEITHER is, the grid does not yet determine it: go and force one more cell inside the cross rather than guessing between them.`,
    ruleTags: ['lat.hiddenSingle.row', 'lat.hiddenSingle.col'],
  },
  {
    id: 'lat-depth-budget',
    subtest: 'latin',
    level: 'sharp',
    title: 'Nine to eleven givens means a full minute — decide up front',
    body: `A sparse grid needs four or more forced fills, and each fill honestly costs 10–15 seconds without notes. That is a minute of your budget. Recognise it from the clue count in the first three seconds and either commit the time or take the best candidate and move on.`,
    ruleTags: ['lat.chain4plus', 'lat.clues.sparse'],
  },
  {
    id: 'lat-easy-protects-the-cross',
    subtest: 'latin',
    level: 'elite',
    title: `On easy grids the target's cross is protected`,
    body: `The easy generator strips cells AWAY from the "?" row and column, keeping them dense so a single elimination finishes the task. So on an easy set, if the cross does not resolve immediately, you have miscounted the letters in it — recount rather than starting a chain.`,
    ruleTags: ['lat.direct'],
  },
  {
    id: 'lat-alphabet-is-a-skin',
    subtest: 'latin',
    level: 'core',
    title: 'Digits, Greek and shapes are the same puzzle',
    body: `The display alphabet is cosmetic — the logic runs on five interchangeable tokens whatever they look like. Practising with the shape or Greek skins breaks the habit of reading letters as words, which is exactly the habit that slows you down when the tokens go abstract.`,
  },
  {
    id: 'lat-hover-aid-is-training-wheels',
    subtest: 'latin',
    level: 'core',
    title: 'The row/column highlight is practice-only — train without it',
    body: `The hover highlight that lights up a cell's row and column is a practice-mode aid; it is simply absent in exam mode, and it will not be there on the day. It is not a setting you switch off — you leave it behind by running exam-mode Latin sets. Do that for the last couple of weeks and you will find the cross-scan has become automatic, or find out that it has not, which is worth knowing early.`,
  },
  {
    id: 'lat-explanation-is-the-shortest-chain',
    subtest: 'latin',
    level: 'sharp',
    title: 'The review explanation is the SHORTEST route, not yours',
    body: `The chain shown in review is the minimal forced sequence — if yours took eight steps and the explanation takes four, the gap is your technique, not your luck. Read those four steps and ask which one you would never have found.`,
  },
  {
    id: 'lat-sparse-means-hidden-single',
    subtest: 'latin',
    level: 'sharp',
    title: 'Sparse grids are hidden-single grids',
    body: `Below about twelve clues, plain elimination stalls almost immediately — there simply are not four letters in any cross. That means the first move is nearly always a hidden single, so start hunting one instead of re-reading rows for a naked single that is not there.`,
    ruleTags: ['lat.clues.sparse', 'lat.hiddenSingle.row', 'lat.hiddenSingle.col'],
  },
  {
    id: 'lat-two-birds-cells',
    subtest: 'latin',
    level: 'elite',
    title: 'A cell in the "?" row that is ALSO a hidden single is the jackpot',
    body: `When a forced fill lands inside the target's own row or column, it does double duty: it is progress, and it directly cuts the target's candidates. Hunt for those first on a hard grid — they turn a five-step chain into a two-step one.`,
    ruleTags: ['lat.chain4plus'],
  },
  {
    id: 'lat-question-mark-is-never-a-given',
    subtest: 'latin',
    level: 'core',
    title: 'The "?" cell is always empty and always uniquely forced',
    body: `Whatever the rest of the grid does, the target has exactly one legal letter — that is guaranteed before the task ever reaches you. So there is never a reason to hedge between two answers: if you have two, you have not finished, and one more hidden-single check will settle it.`,
  },

  /* --------------------------------- pacing ------------------------------- */
  {
    id: 'pace-seventy-five-seconds',
    subtest: 'pacing',
    level: 'core',
    title: '20 tasks, 25 minutes, 75 seconds each',
    body: `That is the average, not the target. The whole art of this exam is spending less than the average on the tasks that deserve less, so the hard ones get more than the average without you panicking.`,
  },
  {
    id: 'pace-thirty-five-then-two-minutes',
    subtest: 'pacing',
    level: 'core',
    title: 'Bank time on the easy ones: 35 seconds each',
    body: `Ten tasks at 35 seconds costs under six minutes and leaves nineteen for the other ten — nearly two minutes apiece. The easy tasks are not where marks are won; they are where the time for the hard ones is bought.`,
  },
  {
    id: 'pace-never-leave-a-blank',
    subtest: 'pacing',
    level: 'core',
    title: 'There is no negative marking — a blank is strictly worse than a guess',
    body: `An unanswered task is scored exactly like a wrong one, so a guess dominates a blank outright. A blind pick is worth a fifth of a mark on a Latin task and a fifth on a five-option equation; on a figure task you must guess BOTH images, which is a ninth of a mark. All of them beat zero, and leaving anything blank is the only strictly irrational move available to you.`,
  },
  {
    id: 'pace-guess-then-move',
    subtest: 'pacing',
    level: 'core',
    title: 'Commit a guess the moment you decide to leave',
    body: `Do not plan to "come back and fill it in" — plan to come back and IMPROVE it. Put a real answer down before you move on, every time, so a clock that runs out costs you nothing.`,
  },
  {
    id: 'pace-figure-tasks-pay-twice',
    subtest: 'pacing',
    level: 'sharp',
    title: 'A figure task needs BOTH images — one right and one wrong scores zero',
    body: `A figure task is one mark, and it is all-or-nothing: Image 1 and Image 2 must both be right. Both come from the same rules, so the second one is nearly free once the work is done — which means abandoning after Image 1 throws away a mark you have already earned. If you are going to guess, guess both; if you have solved the rules, spend the extra fifteen seconds.`,
  },
  {
    id: 'pace-ninety-second-abandon',
    subtest: 'pacing',
    level: 'sharp',
    title: 'The abandon decision happens at 90 seconds, not at three minutes',
    body: `If you have not made real progress by 90 seconds, you are unlikely to make it by 180 — and those extra 90 seconds are two easy tasks you will now rush. Take the best candidate, answer, move.`,
  },
  {
    id: 'pace-clock-checkpoints',
    subtest: 'pacing',
    level: 'sharp',
    title: 'Three clock checks, not thirty',
    body: `Check the timer at task 5, task 10 and task 15 — you want roughly 6, 12 and 19 minutes gone. Glancing at the clock every task burns attention and makes you rush the one you are actually solving.`,
  },
  {
    id: 'pace-forward-only',
    subtest: 'pacing',
    level: 'sharp',
    title: 'Exam mode moves forward only — practise committing',
    body: `CoreForge's exam mode is linear by default, so you answer and advance with no going back (the official navigation behaviour is unconfirmed — practising the stricter version costs you nothing and protects you if it is true). Train the habit of a decisive commit rather than a mental "I'll revisit that".`,
  },
  {
    id: 'pace-two-pass-in-practice',
    subtest: 'pacing',
    level: 'sharp',
    title: 'Use free navigation only in practice',
    body: `Practice with free navigation to build the two-pass instinct — quick sweep, then the hard ones. Then run exam mode to prove you can still perform if that safety net is not there on the day.`,
  },
  {
    id: 'pace-no-notes-ever',
    subtest: 'pacing',
    level: 'core',
    title: 'Practise mentally from day one — no notes in the real exam',
    body: `Every technique you rehearse with a pen is a technique you cannot use. Latin chains and figure traces have to fit in working memory, and that only happens if you have never allowed yourself the crutch.`,
  },
  {
    id: 'pace-warm-up-before',
    subtest: 'pacing',
    level: 'sharp',
    title: 'Do not let task 1 be your warm-up',
    body: `Run a short easy set of each subtest on the morning of the exam. The first task always costs 20 seconds more than it should; you would rather pay that at home than on the clock.`,
  },
  {
    id: 'pace-practise-weakest-last',
    subtest: 'pacing',
    level: 'sharp',
    title: 'Train your weakest subtest when you are tired',
    body: `Accuracy falls in the last subtest of a sitting — that is fatigue, not difficulty. So put your weakest subtest LAST in practice sessions: you are training the state you will actually be in.`,
  },
  {
    id: 'pace-turn-off-instant-feedback',
    subtest: 'pacing',
    level: 'sharp',
    title: 'Turn instant feedback off in the last two weeks',
    body: `Knowing you were right after each answer is a learning aid and a confidence drug — and the exam gives you neither. Switch it off and learn what it feels like to move on without knowing.`,
  },
  {
    id: 'pace-full-core-simulation',
    subtest: 'pacing',
    level: 'sharp',
    title: 'Run at least three full Core simulations',
    body: `Subtest practice teaches the rules; full-length runs teach the endurance and the pacing, which are separate skills. Do three, spaced out, and treat the last one as a dress rehearsal — same time of day, same chair, no interruptions.`,
  },
  {
    id: 'pace-read-the-format-first',
    subtest: 'pacing',
    level: 'core',
    title: 'Identify the task shape in the first three seconds',
    body: `Count the symbols, count the equations, count the givens. Those three-second reads tell you the difficulty band and therefore the budget — before you have solved anything. Starting to solve before you have sized the task is how the clock eats you.`,
  },
  {
    id: 'pace-dont-rush-the-easy-ones-blind',
    subtest: 'pacing',
    level: 'core',
    title: 'Fast is not careless',
    body: `The 35-second easy task still gets its check — a back-substitution, a parity glance, a cross recount. Speed comes from skipping deliberation, not from skipping verification: an easy task you got wrong costs the same mark as a hard one.`,
  },

  /* -------------------------------- mindset ------------------------------- */
  {
    id: 'mind-drill-the-tags',
    subtest: 'mindset',
    level: 'core',
    title: 'Let the rule tags choose your practice',
    body: `Analytics breaks your misses down by the exact rule involved — diagonal bounce, x+1 acceleration, hidden singles in columns. Practising what you are already good at feels great and moves nothing; drill the two worst tags and re-measure in a week.`,
  },
  {
    id: 'mind-mistakes-notebook',
    subtest: 'mindset',
    level: 'core',
    title: 'The mistakes notebook is the highest-value screen in the app',
    body: `Every question you missed is stored and can be re-drilled as a fresh set. A missed question you never revisit is a mistake you have agreed to make again on the day.`,
  },
  {
    id: 'mind-name-the-error',
    subtest: 'mindset',
    level: 'sharp',
    title: 'Name the error, not the topic',
    body: `"I'm bad at figures" is not actionable. "I flip both components at a side wall" is — it names a rule, it is fixable in one session, and you can check it is gone. Every review should end with a sentence of that shape.`,
  },
  {
    id: 'mind-explain-out-loud',
    subtest: 'mindset',
    level: 'sharp',
    title: 'Explain the solution as if teaching it',
    body: `After a hard task, say the full derivation in your head as a sequence of sentences. Anywhere you have to hand-wave is a gap in the rule model, and it is exactly where the exam will catch you.`,
  },
  {
    id: 'mind-review-your-correct-answers',
    subtest: 'mindset',
    level: 'sharp',
    title: 'Review the ones you got right but slowly',
    body: `A correct answer that took 140 seconds is a failure with a lucky ending — on the day, that task costs you two others. Track time per task, not just accuracy, and review the slow correct ones as seriously as the wrong ones.`,
  },
  {
    id: 'mind-no-streak-chasing',
    subtest: 'mindset',
    level: 'core',
    title: 'Points and leagues are motivation, not measurement',
    body: `Streaks and leagues exist to get you back into the chair. Accuracy per rule tag and time per task are what actually predict your score. Enjoy the first, but make decisions from the second.`,
  },
  {
    id: 'mind-recover-fast',
    subtest: 'mindset',
    level: 'core',
    title: 'A blown task costs one mark — dwelling on it costs three',
    body: `The tax on a bad task is paid in the two tasks after it, while you are still replaying it. Close it deliberately: answer, breathe once, read the next question fresh. That habit is trainable and it is worth real marks.`,
  },
  {
    id: 'mind-one-hard-thing-per-session',
    subtest: 'mindset',
    level: 'sharp',
    title: 'Fix one mechanism per session',
    body: `Pick a single mechanism — say, x+1 arithmetic into Image 1 and Image 2 — and hammer it in one sitting until it is boring. Diffuse practice across everything produces diffuse improvement across nothing.`,
  },
  {
    id: 'mind-spaced-not-crammed',
    subtest: 'mindset',
    level: 'sharp',
    title: 'Twenty minutes daily beats three hours on Sunday',
    body: `These are pattern-recognition skills — they consolidate in sleep, not in marathons. A short daily set keeps the rule system live in memory and keeps the recognition fast, which is the thing actually being tested.`,
  },
  {
    id: 'mind-simulate-the-conditions',
    subtest: 'mindset',
    level: 'sharp',
    title: 'Practise in the conditions you will be tested in',
    body: `No notes, no pausing, no music you would not have, no phone within reach. Skills are surprisingly context-bound: everything you rehearse under comfortable conditions gets a discount applied on the day.`,
  },
  {
    id: 'mind-sleep-is-a-technique',
    subtest: 'mindset',
    level: 'core',
    title: 'The night before is not study time',
    body: `Working memory is what this exam measures, and sleep loss cuts it hard — harder than one more practice set adds. Do a light warm-up set the evening before, then stop.`,
  },
  {
    id: 'mind-trust-the-trained-move',
    subtest: 'mindset',
    level: 'elite',
    title: 'Under pressure, do the trained move — do not improvise',
    body: `The techniques here are only worth anything if they fire automatically when your heart rate is up. If you find yourself inventing a new approach mid-task in the exam, that is stress talking; fall back to the checklist — count, classify, solve, verify.`,
  },

  /* --------------------- General Academic Module (GAM) -------------------- */
  {
    id: 'gam-passage-teaches-everything',
    subtest: 'gam',
    level: 'core',
    title: 'The passage contains every fact you need — treat it as the only source',
    body: `GAM questions are answerable from the passage alone; outside knowledge is at best a shortcut and at worst a trap, because distractors are built from plausible-sounding claims the passage never makes. When two options both "sound right", the tiebreaker is always: which one does the text actually say?`,
    ruleTags: ['gam.skill.concept'],
  },
  {
    id: 'gam-skim-structure-first',
    subtest: 'gam',
    level: 'core',
    title: 'Skim the structure, read the questions, then re-read with purpose',
    body: `First pass (≈1 minute): headings, bold terms, what each paragraph is about, where the formula and the table live. Then read the QUESTIONS. Only then re-read the paragraphs that matter, closely. Reading the whole passage deeply before seeing a single question means reading most of it twice.`,
  },
  {
    id: 'gam-formula-is-given',
    subtest: 'gam',
    level: 'core',
    title: 'Formulas are provided — the test is whether you can drive them',
    body: `The real exam does not expect memorized formulas: the passage presents what you need, often in a small table. The skill being tested is disciplined substitution — identify each symbol's value from the text or table, substitute once, compute once. Practise reading a formula table as fast as you read prose.`,
    ruleTags: ['gam.skill.compute'],
  },
  {
    id: 'gam-no-notes-arithmetic',
    subtest: 'gam',
    level: 'core',
    title: 'No notes: structure your mental arithmetic',
    body: `You cannot write anything down, so arithmetic must be staged: simplify BEFORE multiplying (cancel common factors, pull out powers of ten), keep one intermediate number in words ("twelve hundred"), and round-check the magnitude at the end. The numbers in GAM tasks are chosen to be clean — if yours are getting ugly, you took a wrong turn.`,
    ruleTags: ['gam.skill.compute'],
  },
  {
    id: 'gam-units-are-a-free-check',
    subtest: 'gam',
    level: 'sharp',
    title: 'Units are a free answer-checker',
    body: `Carry units through every computation: if the question asks for euros and your expression produces euros per unit, you swapped a ratio. Distractors are regularly built from exactly these swaps — inverted ratios, per-unit vs total, percentage vs absolute — so a five-second unit check eliminates them without redoing the math.`,
    ruleTags: ['gam.skill.compute'],
  },
  {
    id: 'gam-eliminate-on-four',
    subtest: 'gam',
    level: 'core',
    title: 'Four options: eliminate two fast, then decide slowly once',
    body: `Almost every GAM item has two options you can kill quickly — a sign error, an over-generalization ("always", "never"), or a claim the passage contradicts outright. Do that first. A 50/50 decision made carefully beats a 25% blind guess, and blanks score exactly zero, so ALWAYS answer.`,
  },
  {
    id: 'gam-distractors-are-misconceptions',
    subtest: 'gam',
    level: 'sharp',
    title: 'Wrong options are engineered misconceptions — name the error',
    body: `Each distractor encodes a specific mistake: the inverted formula, the swapped condition, the conclusion that overshoots the evidence. When you can say WHY an option is wrong ("that is the ratio upside down"), you are certain; when you can only say it "feels wrong", re-read the relevant sentence before committing.`,
  },
  {
    id: 'gam-chart-axes-first',
    subtest: 'gam',
    level: 'core',
    title: 'Charts: axes and units before lines',
    body: `Before interpreting any figure, read both axis labels and their units aloud in your head. Most chart-reading errors are axis errors — reading a quantity where the chart shows a rate, or a total where it shows a per-period value. Then find the specific feature the question names (an intersection, a plateau, a slope) rather than describing the whole picture.`,
    ruleTags: ['gam.skill.read-chart'],
  },
  {
    id: 'gam-time-budget',
    subtest: 'gam',
    level: 'core',
    title: 'Budget ≈2.5–3 minutes per question, reading included',
    body: `90 minutes for roughly 24–34 questions means each passage block gets about 15–20 minutes: a few minutes of reading buys you 6–8 questions. If a single computation passes the two-minute mark, pick the most defensible remaining option, and move — the next passage starts from zero and pays the same points.`,
  },
  {
    id: 'gam-transfer-questions',
    subtest: 'gam',
    level: 'sharp',
    title: 'Transfer questions: map the scenario onto the passage, term by term',
    body: `When a question introduces a new scenario (a different company, a new substance), it is testing whether you can identify WHICH concept from the passage the scenario instantiates. Explicitly match: who plays the role of X, what plays the role of Y. The wrong options map the scenario onto the neighbouring concept — the one that shares a paragraph with the right one.`,
    ruleTags: ['gam.skill.transfer'],
  },
  {
    id: 'gam-negations-and-extremes',
    subtest: 'gam',
    level: 'sharp',
    title: 'Read stems twice when they contain NOT, EXCEPT, or "most"',
    body: `A stem asking which statement is NOT supported inverts every instinct you have trained on the other questions, and superlatives ("most elastic", "furthest") mean ranking all four options, not verifying one. Slow down exactly there — these stems are where fast readers donate points.`,
  },
  {
    id: 'gam-anchor-answers-in-text',
    subtest: 'gam',
    level: 'elite',
    title: 'Before committing, point at the sentence',
    body: `For conceptual questions, force yourself to locate the specific sentence that makes your option true. If you cannot point at it, you are pattern-matching on vocabulary — which is precisely what the best distractor in the set was built to reward. This one habit converts "usually right" into "reliably right".`,
    ruleTags: ['gam.skill.concept'],
  },
];

export const TRICK_SUBTEST_LABELS: Record<TrickSubtest, string> = {
  figures: 'Figures',
  equations: 'Equations',
  latin: 'Latin Squares',
  gam: 'General Academic Module',
  pacing: 'Pacing & exam craft',
  mindset: 'Mindset & method',
};

export const TRICK_LEVEL_LABELS: Record<TrickLevel, string> = {
  core: 'Core',
  sharp: 'Sharp',
  elite: 'Elite',
};

/** Tricks that address a weakness the analytics screen reports (rule tag). */
export function tricksForRuleTag(tag: string): Trick[] {
  return TRICKS.filter((t) => t.ruleTags?.includes(tag));
}
